export const COMMENT_REPOSITORY = 'COMMENT_REPOSITORY';
export const COMPOSITION_REPOSITORY = 'COMPOSITION_REPOSITORY';
export const POST_REPOSITORY = 'POST_REPOSITORY';
export const POST_SCHEDULE_REPOSITORY = 'POST_SCHEDULE_REPOSITORY';
export const ACCOUNT_REPOSITORY = 'ACCOUNT_REPOSITORY';
